[package]
name = "shpx-geom"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "shpx のジオメトリ表現・WKB エンコーダ・CRS ユーティリティ"

[lints]
workspace = true

[dependencies]
shpx-core  = { path = "../shpx-core" }
serde      = { workspace = true }
serde_json = { workspace = true }
regex      = { workspace = true }
